export const countries=[
    {value:"AF",label:"Afghanistan",code:"93"},
    {value:"AL",label:"Albania",code:"355"},
    {value:"DZ",label:"Algeria",code:"213"},
    {value:"AS",label:"America Samoa",code:"1"},
    {value:"AD",label:"Andorra",code:"376"},
    {value:"AO",label:"Angola",code:"244"},
    {value:"AI",label:"Anguilla",code:"1"},
    {value:"AQ",label:"Antarctica",code:"672"},
    {value:"AG",label:"Antigua and Barbuda",code:"1"},
    {value:"AR",label:"Argentina",code:"54"},
    {value:"AM",label:"Armenia",code:"374"},
    {value:"AW",label:"Aruba",code:"297"},
    {value:"AU",label:"Australia",code:"61"},
    {value:"AT",label:"Austria",code:"43"},
    {value:"AZ",label:"Azerbaijan",code:"994"},
    {value:"BS",label:"Bahamas",code:"1"},
    {value:"BH",label:"Bahrain",code:"973"},
    {value:"BD",label:"Bangladesh",code:"880"},
    {value:"BB",label:"Barbados",code:"1"},
    {value:"BY",label:"Belarus",code:"375"},
    {value:"BE",label:"Belgium",code:"32"},
    {value:"BZ",label:"Belize",code:"501"},
    {value:"BJ",label:"Benin",code:"229"},
    {value:"BM",label:"Bermuda",code:"1"},
    {value:"BT",label:"Bhutan",code:"975"},
    {value:"BA",label:"Bosnia and Herzegovina",code:"387"},
    {value:"BW",label:"Botswana",code:"267"},
    {value:"BR",label:"Brazil",code:"55"},
    {value:"IO",label:"British Indian Ocean Territory",code:"246"},
    {value:"BG",label:"Bulgaria",code:"359"},
    {value:"BF",label:"Burkina Faso",code:"226"},
    {value:"BI",label:"Burundi",code:"257"},
    {value:"KH",label:"Cambodia",code:"855"},
    {value:"CM",label:"Cameroon",code:"237"},
    {value:"CA",label:"Canada",code:"1"},
    {value:"CV",label:"Cape Verde",code:"238"},
    {value:"KY",label:"Cayman Islands",code:"345"},
    {value:"CF",label:"Central African Republic",code:"236"},
    {value:"TD",label:"Chad",code:"235"},
    {value:"CL",label:"Chile",code:"56"},
    {value:"CN",label:"China",code:"86"},
    {value:"CX",label:"Christmas Island",code:"61"},
    {value:"CO",label:"Colombia",code:"57"},
    {value:"KM",label:"Comoros",code:"269"},
    {value:"CG",label:"Republic of the Congo",code:"242"},
    {value:"CK",label:"Cook Islands",code:"682"},
    {value:"CR",label:"Costa Rica",code:"506"},
    {value:"HR",label:"Croatia",code:"385"},
    {value:"CU",label:"Cuba",code:"53"},
    {value:"CY",label:"Cyprus",code:"357"},
    {value:"CZ",label:"Czech Republic",code:"420"},
    {value:"DK",label:"Denmark",code:"45"},
    {value:"DJ",label:"Djibouti",code:"253"},
    {value:"DM",label:"Dominica",code:"1"},
    {value:"DO",label:"Dominican Republic",code:"1"},
    {value:"EC",label:"Ecuador",code:"593"},
    {value:"EG",label:"Egypt",code:"20"},
    {value:"SV",label:"El Salvador",code:"503"},
    {value:"GQ",label:"Equatorial Guinea",code:"240"},
    {value:"ER",label:"Eritrea",code:"291"},
    {value:"EE",label:"Estonia",code:"372"},
    {value:"ET",label:"Ethiopia",code:"251"},
    {value:"FO",label:"Faroe Islands",code:"298"},
    {value:"FJ",label:"Fiji",code:"679"},
    {value:"FI",label:"Finland",code:"358"},
    {value:"FR",label:"France",code:"33"},
    {value:"GF",label:"French Guiana",code:"594"},
    {value:"PF",label:"French Polynesia",code:"689"},
    {value:"GA",label:"Gabon",code:"241"},
    {value:"GM",label:"Gambia",code:"220"},
    {value:"GE",label:"Georgia",code:"995"},
    {value:"DE",label:"Germany",code:"49"},
    {value:"GH",label:"Ghana",code:"233"},
    {value:"GI",label:"Gibraltar",code:"350"},
    {value:"GR",label:"Greece",code:"30"},
    {value:"GL",label:"Greenland",code:"299"},
    {value:"GD",label:"Grenada",code:"1"},
    {value:"GP",label:"Guadeloupe",code:"590"},
    {value:"GU",label:"Guam",code:"1"},
    {value:"GT",label:"Guatemala",code:"502"},
    {value:"GN",label:"Guinea",code:"224"},
    {value:"GW",label:"Guinea-Bissau",code:"245"},
    {value:"GY",label:"Guyana",code:"592"},
    {value:"HT",label:"Haiti",code:"509"},

    {value:"HN",label:"Honduras",code:"504"},
    {value:"HU",label:"Hungary",code:"36"},
    {value:"IS",label:"",code:"354"},
    {value:"IN",label:"",code:"91"},
    {value:"ID",label:"",code:"62"},
    {value:"IQ",label:"",code:"964"},
    {value:"IE",label:"",code:"353"},
    {value:"IL",label:"",code:"972"},
    {value:"IT",label:"",code:"39"},
    {value:"JM",label:"",code:"1"},

    {value:"JP",label:"",code:"81"},
    {value:"JO",label:"",code:"962"},
    {value:"KZ",label:"",code:"77"},
    {value:"KE",label:"",code:"254"},
    {value:"KI",label:"",code:"686"},
    {value:"KW",label:"",code:"965"},
    {value:"KG",label:"",code:"996"},
    {value:"LV",label:"",code:"371"},
    {value:"LB",label:"",code:"961"},
    {value:"LS",label:"",code:"266"},

    {value:"LR",label:"",code:"231"},
    {value:"LI",label:"",code:"423"},
    {value:"LT",label:"",code:"370"},
    {value:"LU",label:"",code:"352"},
    {value:"MG",label:"",code:"261"},
    {value:"MW",label:"",code:"265"},
    {value:"MY",label:"",code:"60"},
    {value:"MV",label:"",code:"960"},
    {value:"ML",label:"",code:"223"},
    {value:"MT",label:"",code:"356"},

    {value:"MH",label:"",code:"692"},
    {value:"MQ",label:"",code:"596"},
    {value:"MR",label:"",code:"222"},
    {value:"MU",label:"",code:"230"},
    {value:"YT",label:"",code:"262"},
    {value:"MX",label:"",code:"52"},
    {value:"MC",label:"",code:"377"},
    {value:"MN",label:"",code:"976"},
    {value:"ME",label:"",code:"382"},
    {value:"MS",label:"",code:"1"},

    {value:"MA",label:"",code:"212"},
    {value:"MM",label:"",code:"95"},
    {value:"NA",label:"",code:"264"},
    {value:"NR",label:"",code:"674"},
    {value:"NP",label:"",code:"977"},
    {value:"NL",label:"",code:"31"},
    {value:"AN",label:"",code:"599"},
    {value:"NC",label:"",code:"687"},
    {value:"NZ",label:"",code:"64"},
    {value:"NI",label:"",code:"505"},

    {value:"NE",label:"",code:"227"},
    {value:"NG",label:"",code:"234"},
    {value:"NU",label:"",code:"683"},
    {value:"NF",label:"",code:"672"},
    {value:"MP",label:"",code:"1"},
    {value:"NO",label:"",code:"47"},
    {value:"OM",label:"",code:"968"},
    {value:"PK",label:"",code:"92"},
    {value:"PW",label:"",code:"680"},
    {value:"PA",label:"",code:"507"},

    {value:"PG",label:"",code:"675"},
    {value:"PY",label:"",code:"595"},
    {value:"PE",label:"",code:"51"},
    {value:"PH",label:"",code:"63"},
    {value:"PL",label:"",code:"48"},
    {value:"PT",label:"",code:"351"},
    {value:"PR",label:"",code:"1"},
    {value:"QA",label:"",code:"974"},
    {value:"RO",label:"",code:"40"},
    {value:"RW",label:"",code:"250"},

    {value:"WS",label:"",code:"685"},
    {value:"SM",label:"",code:"378"},
    {value:"SA",label:"",code:"966"},
    {value:"SN",label:"",code:"221"},
    {value:"RS",label:"",code:"381"},
    {value:"SC",label:"",code:"248"},
    {value:"SL",label:"",code:"232"},
    {value:"SG",label:"",code:"65"},
    {value:"SK",label:"",code:"421"},
    {value:"SI",label:"",code:"386"},

    {value:"SB",label:"",code:"677"},
    {value:"ZA",label:"",code:"27"},
    {value:"GS",label:"",code:"500"},
    {value:"ES",label:"",code:"34"},
    {value:"LK",label:"",code:"94"},
    {value:"SD",label:"",code:"249"},
    {value:"SR",label:"",code:"597"},
    {value:"SZ",label:"",code:"268"},
    {value:"SE",label:"",code:"46"},
    {value:"CH",label:"",code:"41"},

    {value:"TJ",label:"",code:"992"},
    {value:"TH",label:"",code:"66"},
    {value:"TG",label:"",code:"228"},
    {value:"TK",label:"",code:"690"},
    {value:"TO",label:"",code:"676"},
    {value:"TT",label:"",code:"1"},
    {value:"TN",label:"",code:"216"},
    {value:"TR",label:"",code:"90"},
    {value:"TM",label:"",code:"993"},
    {value:"TC",label:"",code:"1"},

    {value:"TV",label:"",code:"688"},
    {value:"UG",label:"",code:"256"},
    {value:"UA",label:"",code:"380"},
    {value:"AE",label:"",code:"971"},
    {value:"GB",label:"",code:"44"},
    {value:"US",label:"",code:"1"},
    {value:"UY",label:"",code:"598"},
    {value:"UZ",label:"",code:"998"},
    {value:"VU",label:"",code:"678"},
    {value:"WF",label:"",code:"681"},

    {value:"YE",label:"",code:"967"},
    {value:"ZM",label:"",code:"260"},
    {value:"ZW",label:"",code:"263"},
    {value:"BO",label:"",code:"591"},
    {value:"BN",label:"",code:"673"},
    {value:"CC",label:"",code:"61"},
    {value:"CD",label:"",code:"243"},
    {value:"CI",label:"",code:"225"},
    {value:"FK",label:"",code:"500"},
    {value:"GG",label:"",code:"44"},

    {value:"VA",label:"",code:"379"},
    {value:"HK",label:"",code:"852"},
    {value:"IR",label:"",code:"98"},
    {value:"IM",label:"",code:"44"},
    {value:"JE",label:"",code:"44"},
    {value:"KP",label:"",code:"850"},
    {value:"KR",label:"",code:"82"},
    {value:"LA",label:"",code:"856"},
    {value:"LY",label:"",code:"218"},
    {value:"MO",label:"",code:"853"},

    {value:"MK",label:"",code:"389"},
    {value:"FM",label:"",code:"691"},
    {value:"MD",label:"",code:"373"},
    {value:"MZ",label:"",code:"258"},
    {value:"PS",label:"",code:"970"},
    {value:"PN",label:"",code:"872"},
    {value:"RE",label:"",code:"262"},
    {value:"RU",label:"",code:"7"},
    {value:"BL",label:"",code:"590"},
    {value:"SH",label:"",code:"290"},

    {value:"KN",label:"",code:"1"},
    {value:"LC",label:"",code:"1"},
    {value:"MF",label:"",code:"590"},
    {value:"PM",label:"",code:"508"},
    {value:"VC",label:"",code:"1"},
    {value:"ST",label:"",code:"239"},
    {value:"SO",label:"",code:"252"},
    {value:"SJ",label:"",code:"47"},
    {value:"SY",label:"",code:"963"},
    {value:"TW",label:"",code:"886"},

    {value:"TZ",label:"",code:"255"},
    {value:"TL",label:"",code:"670"},
    {value:"VE",label:"",code:"58"},
    {value:"VN",label:"",code:"84"},
    {value:"VG",label:"",code:"284"},
    {value:"VI",label:"",code:"340"},
    {value:"EH",label:"",code:"121"},

]